### ISSUE TITLE
Error in embed() from AchillesEncoder.py 

### ISSUE THREAD

**Issue by Coke-Zhang** [wooyongc/Benisse#7]
Hello, I want to integrate BCR and gene expression on single cell levels with your tools-Benisse. But I met some errors. Please debug:
1. Step 1: Generating BCR embedding with  AchillesEncoder.py of python files.
the output files have error:
`contigs_encoded1$index[1:5]
[1] "<map object at 0x7f18560089d0>" "<map object at 0x7f18560089d0>"
[3] "<map object at 0x7f18560089d0>" "<map object at 0x7f18560089d0>"
[5] "<map object at 0x7f18560089d0>"`

I found the error in function embed() (lines 118-133) from AchillesEncoder.py:
 `feature_array_tmp['index']=cdr3_seq`
feature_array=pd.DataFrame(feat_cdr.cpu().numpy())
feature_array['index']=cdr3_seq
feature_array_tmp=pd.DataFrame(feat_cdr.cpu().numpy())
feature_array_tmp['index']=cdr3_seq`

Please DeBug!!!

**Comment by wooyongc** [comment]
https://github.com/wooyongc/Benisse/issues/8#issue-1332638067
