### ISSUE TITLE
Error in update_A() from /R/Benisse.R

### ISSUE THREAD

**Issue by Coke-Zhang** [wooyongc/Benisse#8]
I also met some errors, Please debug:
2. Step 2: Run the core Benisse model with Benisse.R with your example data and output CDR files.
the error is :
`Error in 2 * data[[7]] + 16 * data[[1]] * data[[2]]^2 * (-U - t(U) + 2 *  : 
  非整合陈列
此外: Warning message:
In par * as.vector(data[[7]]) : 长的对象长度不是短的对象长度的整倍数`

I found the error in: 
`results=Benisse(hyper_para,cdr3exp,t,meta_dedup,exp_data,
              max_iter,save_path,mode,stop_cutoff)`
More: 
`A=update_A(master_dist_e,phi,meta_dedup,SI,I,A,R,Q,LS,hyper_para)`

More:
`optim_results=optim(as.vector(A[par_which]),fn=fn,gr=gr,method='L-BFGS-B',
                      lower=lower,upper=upper,data=data,control=control_list)$par`

More:
`# bug in 
  gr=function(par0,data){
    par=data[[10]]
    par[data[[9]]]=par0
    U=as.vector(diag(rowSums(par))-par)-
      (data[[5]]-data[[8]]-data[[4]]/data[[1]])/(4*data[[2]])+
      data[[6]]*data[[3]]
    gradients=2*data[[7]]+16*data[[1]]*data[[2]]^2*(-U-t(U)+2*diag(U))
    gradients[data[[9]]]
  }`

Also I try to set 
`t0 = Sys.time()
  gr=NULL
  optim_results=optim(as.vector(A[par_which]),fn=fn,gr=gr,method='L-BFGS-B',
                      lower=lower,upper=upper,data=data,control=control_list)$par
  t1 = Sys.time()
  print(paste0('Need Times: ', t1-t0))
`
But this step can't run.

Please Debug !!!

**Comment by wooyongc** [comment]
Hi, thank you for having an interest in our work.

We have tested our program on different machines and systems, but we failed to replicate your problem.
Please check your dependencies and input formats.

Thank you.
