### ISSUE TITLE
Colouring BCR networks

### ISSUE THREAD

**Issue by hannasj** [wooyongc/Benisse#9]
Hi, Thanks for providing Benisse.I have several questions please:
1. I wondered if it is possible to colour the graph by which network the BCRs are in, as in Fig 3a in the paper please? i.e. to make it so that all vertices that are connected, even if there is an intermediate vertex in the middle, have the same colour?

2. is it possible to draw out from your data the components of each BCR network separately?

3. In the paper when you say "the weight of each edge represents the similarity between two BCRs." what does this mean in the graph? For example in Fig3a all lines appear the same thickness. Does the length of the line represent the difference in CDR3H sequence? 

Many thanks for your help

**Comment by wooyongc** [comment]
Hi, Thank you for having an interest in our work. Sorry for the late reply!

To answer your question 3 first, the answer is no, but I have reflected in my code below to demonstrate this.

The graph can be drawn from our output from the Benisse, using the igraph package.

```{r}
library("igraph")

# Read in the data generated by Benisse
adjmatrix <- as.matrix(read.csv("/Users/noahchang/Downloads/sparse_graph.txt", sep = " ", header =  F))
d <- as.matrix(read.csv("/Users/noahchang/Downloads/latent_dist.txt", sep = " ", header = F))
encoded <- read.csv("/Users/noahchang/Downloads/encoded_10x_NSCLC.csv", sep = ",", header = T)

# Create an weighted undirected graph from the sparse_graph.txt
g <- graph_from_adjacency_matrix(
  adjmatrix,
  mode = c("undirected"),
  weighted = TRUE
)

# Create dictionary of Vertex name AA sequence from our encoded_10x_NSCLC.csv
encoded$X <- paste("V", as.character(rownames(encoded)), sep = "")
encoded <- encoded[c("X", "index")]

# Change label using the dict
V(g)$label <- as.character(dict[V(g)$name])

# Convert distance matrix to coordinates using Classic MDS
# http://en.wikipedia.org/wiki/Multidimensional_scaling
mds <- cmdscale(d, k = 2)
rownames(mds) <- colnames(d)

# Remove unconnected nodes (singletons)
isolated = which(degree(g)==0)
g_nosingleton <- delete.vertices(g, isolated)

# Detect dense community
fc <- fastgreedy.community(g_nosingleton)
# Assign colors based on the community membership
colors <- rainbow(max(membership(fc)))

# Plot the graph
plot(g_nosingleton,
     vertex.color=colors[membership(fc)], 
     vertex.size=3, 
     vertex.label = NA,
     axes = T,
     # Grab only the rows from mds by the vertices in our current graph
     layout = as.matrix(mds [rownames(mds) %in% V(g_nosingleton)$name, ]), 
     edge.width = E(g_nosingleton)$weight)

# Separate the graph into lists of graph, depending on the connectivity
components <- decompose(g_nosingleton, min.vertices = 5)

# Plot the first component(connected subgraph)
plot(components[[1]],
     axes = T,
     layout = as.matrix(mds [rownames(mds) %in% V(components[[1]])$name, ] ))

```

![example_graph](https://user-images.githubusercontent.com/74789088/197042683-1323bc7d-c91d-4030-a85e-15cd82a8f60b.png)
![component_1](https://user-images.githubusercontent.com/74789088/197042688-44796848-ab8c-4e57-805d-3adb8cf1f0a7.png)

Please let me know if you have further questions

**Comment by hannasj** [comment]
That's great, thanks for your help
